SStest/Models/RoleSelect/Operations.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SStest.Models;

namespace SStest.Models.RoleSelect
{
    public static class Operations
    {
        public static List<Categories> GetCategories(List<int> RolesID)//用角色抓出推薦產品category的函式
        {
            List<Categories> Categories = new List<Categories>();
            if (RolesID != null)
            {
                using (SmartShoppingEntities db = new SmartShoppingEntities())
                {
                    for (int i = 0; i < RolesID.Count; i++)
                    {

                        int id = RolesID[i];
                        //List<RolesDetail> rolesd = db.RolesDetail.Where(p => p.Roles_ID == RolesID[i]);
                        var q = from r in db.RolesDetail
                                where r.Roles_ID == id
                                select r;
                        foreach (var item in q)
                        {

                            Categories category = db.Categories.Where(c => c.Category_ID == item.Categories_ID).First();
                            if (!Categories.Contains(category))
                            {
                                Categories.Add(category);
                            }

                        }

                    }


                }

            }
            

            return Categories;
        }

        //public static List<Categories> GetList() { }
    }
}

SStest/Controllers/LogInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SStest.Models;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;

namespace SmartShoppingWebsite.Controllers
{
    
    public class LogInController : Controller
    {
        // GET: LogIn
        SmartShoppingEntities db = new SmartShoppingEntities();
        int MemberID;
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Members member)
        {
            //先做一個salt再存Password
            System.Security.Cryptography.RNGCryptoServiceProvider rng = new System.Security.Cryptography.RNGCryptoServiceProvider();
            byte[] buf = new byte[15];
            rng.GetBytes(buf);
            string salt = Convert.ToBase64String(buf);
          
            string Password = member.Password;
            Password = FormsAuthentication.HashPasswordForStoringInConfigFile(Password + salt, "sha1");
            member.Password = Password;
            
            db.Members.Add(member);
            try
            {
                db.SaveChanges();
            }
            catch (Exception ex)
            {

                throw;
            }
            
            return View();
        }

        public ActionResult test()
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.message= User.Identity.GetUserId();
            }
            return View();
        }

        public ActionResult RoleSelect()
        {
            
            return View(db.Roles.ToList());
        }
        //被點的RoleID
        [HttpPost]
        public ActionResult RoleSelected(List<int> id)
        {
            //List<int> SelectedRole = new List<int>();
            //if (!SelectedRole.Contains(id))
            //{
            //    SelectedRole.Add(id);
            //}
            //else
            //{
            //    SelectedRole.Remove(id);
            //}
           //id get categories list function
            List<Categories> categories = SStest.Models.RoleSelect.Operations.GetCategories(id);
            var q = from p in categories
                    select new { categoryid = p.Category_ID, categoryname = p.CategoryName };

            return Json(q.ToList(),JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CategorySelected(List<int> id)
        {

            //if (System.Web.HttpContext.Current.Session["CategorySelected"]==null)
            //{
            //    System.Web.HttpContext.Current.Session["CategorySelected"] = id;
            //}

            //幫她存起來
            if (User.Identity.IsAuthenticated)
            {
                string aspid = User.Identity.GetUserId();
                MemberID = db.Members.Where(m => m.Id == aspid).Select(m => m.Member_ID).First();
            }
            //先做一個PList
            PList pl = new PList();
            pl.PList_ID = db.PList.Max(p => p.PList_ID) + 1;
            pl.ListName = "我的購物清單";
            pl.Member_ID = MemberID;
            db.Entry(pl).State = EntityState.Added;

            //寫到這裡
            foreach (var item in id)
            {
                ShoppingList sl = new ShoppingList();
                sl.PList_ID = pl.PList_ID;
                sl.ListName = db.Categories.Where(c => c.Category_ID == item).Select(c => c.CategoryName).FirstOrDefault();
                sl.Active = true;
                db.Entry(sl).State = EntityState.Added;
            }
            db.SaveChanges();
            return Content("Success");

        }

    }
}

SStest/Views/LogIn/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<link href="~/Content/LogIn.css" rel="stylesheet" />

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-1">
                <div class="signup-form">
                    <h2>登入</h2>
                    <form action="/LogIn/CheckMember" method="post" enctype="multipart/form-data">

                        <input type="text" name="Username" placeholder="帳號" />
                        <input type="password" name="Password" placeholder="密碼" />


                        <button type="submit" class="btn btn-default">登入</button>
                    </form>

                </div>
            </div>
            <div class="col-sm-2">
                <h2 class="or">或</h2>
            </div>
            <div class="col-sm-4">
                <div class=" signup-form">
                    <h2>註冊會員</h2>
                    <form action="/LogIn/Index" method="post" enctype="multipart/form-data">
                        <input type="text" name="MemberName" placeholder="姓名" />
                        <input type="text" name="Username" placeholder="帳號" />
                        <input type="password" name="Password" placeholder="密碼" />
                        <input type="email" name="Email" placeholder="Email" />

                        <button type="submit" class="btn btn-default">註冊</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</section>

SStest/Views/LogIn/RoleSelect.cshtml
@model IEnumerable<SStest.Models.Roles>
@{
    List<int> id = new List<int>();
    id.Add(1);
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>RoleSelect</title>
    <style>
        /** {
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
}*/


#mscontainer{
    
    height:400px;
}
.masonry{
    width:600px;
    margin:30px auto;
}


.masonry .item { 
  width:  120px;
  height: 60px;
  float: left;
  background: #808080;
  border: 1px solid;
  border-color: #E0E0E0;
  border-radius: 5px;
  text-align:center;
  color:white;
  margin-bottom: 10px;
  padding:0;
  font-size:20px;
  font-weight:bold;
}
.item.w2 {  width:  180px;
  height: 60px;
  float: left;
  background: #808080;
  border: 1px solid;
  border-color: #E0E0E0;
  border-radius: 5px;
  text-align:center;/*上下也要*/
  padding:10px 0px 10px 0px;
  color:white;
  margin-bottom: 10px;
  opacity:0.7;
}

.item:hover {
  background: #00CACA;
  border-color: white;
  cursor: pointer;
  opacity:0.5;
}

.item.gigante {
  width: 210px;
  height: 90px;
 background-color:  #00CACA; 
 padding:25px 0px 20px 0px;
 opacity:1;

}

    </style>
</head>
<body>
    <div style="margin:10px auto; text-align:center; font-size:20px;font-weight:bold;">請選擇符合您的身分或描述, 我們將為您量身訂做購物清單...</div>

    <div class="masonry js-masonry" data-masonry-options='{ "columnWidth": 60@*, "gutter": 5*@  }'>
        <!--"isFitWidth":true-->
                @foreach (var _role in Model)
                {
                    <a id="aroles" onclick="RoleSelected('@_role.Roles_ID')" href="javascript:void(0);"><div class="item w2">@_role.RolesName</div></a>
                }
        
        @*<div class="item">上班族</div>*@
       
        <!--每一個項目創一個div, 同樣的大小設同樣的class-->
    </div>
    @*<button type="button" class="btn btn-default get" style="float:right">@Html.ActionLink("click", "RoleSelected", "LogIn", new { id=id})</button>
        <button type="button" class="btn btn-default get" style="float:right">下一步 >></button>*@
    <div id="idToRegister">
        <a id="aok" onclick="RoleSelected(0)" href="javascript:void(0);" class=" btn btn-primary get" role="button" style="float:right">
            下一步 >>
        </a>
    </div>
    
    
        @section scripts{
            <script src="~/Scripts/masonry.pkgd.min.js"></script>
            <script src="https://rawgithub.com/desandro/classie/master/classie.js"></script>
            <script>


    docReady(function () {

        var container = document.querySelector('.masonry');
        //notifElem = document.querySelector('#notification');
        var msnry = new Masonry(container, {
            columnWidth: 60
        });

        msnry.on('layoutComplete', function (msnryInstance, laidOutItems) {
            //notify('Masonry layout completed on ' + laidOutItems.length + ' items');
        });

        eventie.bind(container, 'click', function (event) {
            // don't proceed if item was not clicked on
            if (!classie.has(event.target, 'item')) {
                return;
            }
            // change size of item via class
            classie.toggle(event.target, 'gigante');
            // trigger layout
            msnry.layout();
        });

    });
    var SelectedRole = [];

    function RoleSelected(RoleID) {


        if ($.inArray(RoleID, SelectedRole) == -1 && RoleID !== 0) {
            SelectedRole.push(RoleID);

        }
        else if ($.inArray(RoleID, SelectedRole) !== -1 && RoleID !== 0) {
            SelectedRole = $.grep(SelectedRole, function (value) {
                return value != RoleID;
            })
        } else if (RoleID == 0) {



            $.ajax({
                type: 'POST',
                url: '@Url.Action("RoleSelected","LogIn")',
                data: { id: SelectedRole }

            })
            .done(function (datas) {

                SelectedRole = [];
                var category;
                $('.masonry').empty();
                $.each(datas, function (i, category) {


                    var categoryid = category.categoryid;
                    var div = $('<div></div>').text(category.categoryname).addClass('item w2').val(category.categoryid);
                    div.hide().fadeIn(1000);

                    var a = $('<a class="arole" href="javascript:void(0);"></a>').append(div);

                    //處理動態產生事件綁定
                    a.click(function () { RoleSelected(categoryid) })

                    $('.masonry').append(a);

                })//==End of each==//

                $('#aok').click(function (event) {
                    
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("CategorySelected", "LogIn")',
                        data: { id: SelectedRole }

                    })
                        .done(function (datas) {
                        //$('#aok').remove();
                        @*$('#idToRegister').append(@Html.ActionLink("下一步","Register","Account", routeValues: null, htmlAttributes: new { id = "registerLink" }))*@
                            location.href = "../ShoppingList/ShoppingList";

                    })
                })

            })


        }

    }

</script>
        }

</body>
</html>

SStest/Views/LogIn/RoleSelected.cshtml
@model IEnumerable<SStest.Models.Categories>
@{
    ViewBag.Title = "RoleSelected";
}
<!DOCTYPE html>
<html>
<head>
    <title>RoleSelect</title>
    <style>
        /** {
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
}*/


#mscontainer{

    height:400px;
}
.masonry{
    width:600px;
    margin:30px auto;
}


.masonry .item {
  width:  120px;
  height: 60px;
  float: left;
  background: #808080;
  border: 1px solid;
  border-color: #E0E0E0;
  border-radius: 5px;
  text-align:center;
  color:white;
  margin-bottom: 10px;
  padding:0;
  font-size:20px;
  font-weight:bold;
}
.item.w2 {  width:  180px;
  height: 60px;
  float: left;
  background: #808080;
  border: 1px solid;
  border-color: #E0E0E0;
  border-radius: 5px;
  text-align:center;/*上下也要*/
  padding:10px 0px 10px 0px;
  color:white;
  margin-bottom: 10px;}

.item:hover {
  background: #00CACA;
  border-color: white;
  cursor: pointer;
  opacity:0.5;
}

.item.gigante {
  width: 210px;
  height: 90px;
 background-color:  #00CACA;
 padding:25px 0px 20px 0px;
}
        </style>
    </head>
<body>
    <h2>RoleSelected</h2>
    <div style="margin:10px auto; text-align:center; font-size:20px;font-weight:bold;">請點選您常購買的商品...</div>

    <div class="masonry js-masonry" data-masonry-options='{ "columnWidth": 60@*, "gutter": 5*@  }'>
        <!--"isFitWidth":true-->
        @foreach (var _role in Model)
        {
            <a  href="javascript:void(0);"><div class="item w2">@_role.CategoryName</div></a>
        }

        @*<div class="item">上班族</div>*@

        <!--每一個項目創一個div, 同樣的大小設同樣的class-->
    </div>

    <button type="button" class="btn btn-default get" style="float:right">下一步 >></button>

    <a onclick="SendRoleSelected()" href="javascript:void(0);" class=" btn btn-default get" role="button" style="float:right">
        OK
    </a>
</body>
</html>

SStest/Views/LogIn/test.cshtml
@{
    ViewBag.Title = "test";
}

<h2>@ViewBag.message</h2>