SStest/Controllers/MemberCenterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SStest.Models;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace SStest.Controllers
{
    public class MemberCenterController : Controller
    {
        SmartShoppingEntities db = new SmartShoppingEntities();
        int MemberID;
        // GET: MemberCenter
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CancelEmailAd(bool Confirmed)
        {
            ViewBag.Confirmed = Confirmed;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CancelAd(Members member)
        {
            //get member with the email, save adok to false
            if (ModelState.IsValid)
            {
                var user = db.Members.Where(c=>c.Email==member.Email).First();
                if (user!=null)
                {
                    user.AdOK = false;
                    db.Entry(user).State = EntityState.Modified;
                    db.SaveChanges();
                }
                
            }
            return RedirectToAction("CancelEmailAd", new { Confirmed=true});
        }

        [HttpGet]
        [Authorize]
        public ActionResult ModifyMemberData(int MemberId = 1)
        {
            if (User.Identity.IsAuthenticated)
            {
                string aspid = User.Identity.GetUserId();
                MemberID = db.Members.Where(m => m.Id == aspid).Select(m => m.Member_ID).First();
            }
            var q = db.Members.Where(m => m.Member_ID == MemberID).FirstOrDefault();
            return View("ModifyMemberData", q);
        }

        [HttpPost]
        [Authorize]
        public ActionResult ModifyMemberData(Members _Members)
        {
            if (ModelState.IsValid)
            {
                HttpPostedFileBase file = Request.Files[0];
               
                
                var imgSize = file.ContentLength;
                byte[] imgByte = new Byte[imgSize];
                file.InputStream.Read(imgByte, 0, imgSize);
                _Members.M_Picture = imgByte;
                if (_Members.Birthdate!=null)
                {
                    
                    DateTime d = new DateTime();
                    d=(DateTime)_Members.Birthdate;
                    d.ToShortDateString();
                    _Members.Birthdate = d;
                }
                
                
                db.Entry(_Members).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ModifyMemberData");

            }

            return View();
        }
        public ActionResult GetImagebytes(int id=1)
        {
            if (User.Identity.IsAuthenticated)
            {
                string aspid = User.Identity.GetUserId();
                MemberID = db.Members.Where(m => m.Id == aspid).Select(m => m.Member_ID).First();
            }
            var q = db.Members.Where(m => m.Member_ID == MemberID).Select(m => m.M_Picture).FirstOrDefault();
            return File(q, "image/jpeg");
        }
    }
}

SStest/Views/MemberCenter/CancelEmailAd.cshtml
@model SStest.Models.Members


<h2>取消訂閱</h2>
@if (!ViewBag.Confirmed)
{
    <p>如果您不想收到 Smart Shopping 所發送的電子郵件，請輸入您的電子信箱。</p>
    <hr />
    using (Html.BeginForm("CancelAd", "MemberCenter",FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="login-form">
            <h5>Email</h5>
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            <div class="form-group">
                <input type="submit" value="取消訂閱" />
            </div>
        </div>
    }

}
else
{
    <p>您的取消訂閱設定已更新。</p>
    <p>謝謝!</p>
    <hr />
    @Html.ActionLink("回首頁", "Index", "Home");
    
    <br /><br />
}

SStest/Views/MemberCenter/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

SStest/Views/MemberCenter/ModifyMemberData.cshtml
@model SStest.Models.Members
@{
    ViewBag.Title = "會員資料修改";
}
@section css{
    <style>

    .form-horizontal{
        margin-top:60px;

    }
    </style>
    
    }
<h2>@ViewBag.Title</h2>
<div id="changesaved"><span class="label label-success">變更已儲存</span></div>

@using (Html.BeginForm("ModifyMemberData", "MemberCenter", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
{

        
                @Html.HiddenFor(m => m.Member_ID)
    @Html.HiddenFor(m => m.Id)
    <form class="form-horizontal member">
        <div class="form-group">
            @Html.Label("MemberName", "姓名", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                @Html.TextBoxFor(m => m.MemberName, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Username", "帳號", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.Label("Birthdate", "生日", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                @Html.TextBoxFor(m => m.Birthdate, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("TelPhone", "聯絡電話", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                @Html.TextBoxFor(m => m.TelPhone, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("MobilePhone", "行動電話", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                @Html.TextBoxFor(m => m.MobilePhone, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Address", "聯絡地址", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Email", "電子郵件", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("M_Picture", "個人照片", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                @Html.TextBox("Picture", null, new { type = "file", @class = "form-control" })
            </div>


        </div>
        <div class="form-group">
            @Html.Label("M_Picture", "圖片", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                <img id="img1" src="@Url.Action("GetImagebytes", "MemberCenter", new {id = Model.Member_ID })" style="width:200px" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button id="changesaved" onclick="Save()" type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-save"></span> 儲存</button>
            </div>
        </div>
    </form>

}

@*@section aside{
    <img id="img1" style="width:200px" />
}*@

@section scripts{
    <script>
        $('#Picture').on("change", function () {
        var reader = new FileReader();
        reader.readAsDataURL(this.files[0]);
        reader.addEventListener("load", function (event) {
            $('#img1').attr("src", event.target.result);
        }, false);

        
    })
        $(function () {
            
            $('#changesaved').hide();

        })

        function Save() {
            var reader = new FileReader();
            var r = $('#Picture')
            reader.readAsDataURL(r.files[0]);
        }
    </script>
}